[tool.ruff]
line-length = 80
target-version = "py310"

[tool.ruff.lint]
select = [
  "E",   # pycodestyle errors
  "W",   # pycodestyle warnings
  "F",   # pyflakes
  "Q",   # flake8-quotes
  "UP",  # pyupgrade
  "I",   # isort
  "N",   # pep8-naming
  "PTH", # flake8-use-pathlib
  "C4",  # flake8-comprehensions
  "NPY", # numpy
  "TC",  # type checking
]
